# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Paul Von Schrottky - Senior iOS Engineer
email: paulvonschrottky@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Senior iOS Engineer specializing in Swift, SwiftUI, and remote iOS development. 
  Previously at Automattic (Day One) & WordPress Mobile. 10+ years building iOS apps 
  for millions of users. Available for US remote work via LLC - no visa sponsorship needed.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guarani.github.io" # the base hostname & protocol for your site

# SEO and Social
keywords: "Senior iOS Engineer, Swift Developer, SwiftUI, Remote iOS Developer, iOS Consultant, Automattic, WordPress Mobile, Paraguay Developer"
twitter_username: pschrottky
github_username: guarani
linkedin_username: paulvs
stackoverflow: users/1305067/paulvs

# Author and profile
author: Paul Von Schrottky
profile_image: "/assets/images/profile.png"
location: "Asunción, Paraguay"
timezone: "America/Asuncion"

# Professional details for structured data
job_title: "Senior iOS Engineer"
company: "Independent Contractor"
years_experience: 10
specialties: ["Swift", "SwiftUI", "UIKit", "iOS", "Remote Work", "Team Leadership"]

# Social links for structured data
social:
  - platform: "GitHub"
    url: "https://github.com/guarani"
  - platform: "LinkedIn" 
    url: "https://linkedin.com/in/paulvs"
  - platform: "Twitter"
    url: "https://twitter.com/pschrottky"
  - platform: "Stack Overflow"
    url: "https://stackoverflow.com/users/1305067/paulvs"

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
