# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://guarani.github.io/
title: Paul Von Schrottky - Senior iOS Engineer
author: Paul Von Schrottky
description: Senior iOS Engineer | Swift, SwiftUI | Remote-First | Available via US-based LLC
avatar: profile.png
email: paulvonschrottky@gmail.com
github: guarani # username
twitter: pschrottky
linkedin: paulvs
stackoverflow: users/1305067/paulvs   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus 
disqus.short_name: guarani-github-io 
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
